# build flask app 
FROM python:3.8-slim-buster as base
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y curl
COPY app.py .
EXPOSE 5000
CMD ["python", "app.py"]
