receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:3030"


exporters:
  otlp:
    # disable tls
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]